options:
  - enableCompatibility
mkDirs:
  - system
  - system/apis
  - services
  - temporary
  - user
  - apps
compileFiles:
  - system/bootloader.lua
  - system/krnl.lua
  - system/installer.lua
  - system/liveinst.lua
  - system/apis/col.lua
  - system/apis/rd.lua
  - system/apis/fs.lua
  - system/apis/tutils.lua
  - system/apis/ui.lua
  - services/elevator.lua
  - services/elevatorStep.lua
  - services/elevatorSrv.lua
  - services/shell.lua
  - services/pms.lua
  - apps/init.lua
  - apps/shell.lua
  - apps/cd.lua
  - apps/ls.lua
  - apps/mv.lua
  - apps/cp.lua
  - apps/cat.lua
  - apps/rm.lua
  - apps/mkdir.lua
  - apps/uitest.lua
  - apps/kmsg.lua
  - startup.lua
nrFiles:
  - services/enabled
  - config/passwd
  - config/aboot
  - config/arcshell
  # - config/hostname
