options:
  - enableCompatibility
mkDirs:
  - system
  - system/apis
  - services
  - user
  - apps
compileFiles:
  - system/bootloader.lua
  - system/krnl.lua
  - system/installer.lua
  - system/apis/col.lua
  - system/apis/red.lua
  - system/apis/fs.lua
  - apps/init.lua
  - startup.lua
nrFiles:
  - services/elevator.lua
  - services/elevatorStep.lua
  - services/elevatorSrv.lua
  - services/enabled
  - config/passwd
  - config/aboot
