options:
  - enableCompatibility
mkDirs:
  - system
  - system/apis
  - user
  - apps
compileFiles:
  - system/bootloader.lua
  - system/passwd
  - system/krnl.lua
  - system/installer.lua
  - apps/elevator.lua
  - apps/init.lua
  - system/apis/col.lua
  - system/apis/red.lua
  - startup.lua
nrFiles:
  - system/passwd
