options:
  - enableCompatibility
mkDirs:
  - system
  - system/libs
  - user
  - apps
compileFiles:
  - system/bootloader.lua
  - system/passwd
  - system/krnl.lua
  - system/installer.lua
  - apps/elevator.lua
  - apps/init.lua
  - startup.lua
nrFiles:
  - system/passwd
